<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' City : Ташкент' => ' Ташкент',
    ' для бэкэнда и' => ' для бэкэнда и',
    ' или заказы' => ' или заказы',
    '10 июнь 1998' => '10 июнь 1998',
    'Age' => 'Возраст ',
    'Birthday' => 'день рождения',
    'Bootstrap, Javascript, Vuejs' => 'Bootstrap, Javascript, Vuejs',
    'Call' => 'Вызов',
    'City' => 'город',
    'Degree' => 'степень',
    'Elmurodov_Javohir' => 'Эльмуродов_Жaвохир',
    'Freelance:' => 'Freelance: ',
    'Frontend, Backend разработчик' => 'Frontend, Backend разработчик',
    'Frontend/Backend  Bеб-разработчик.' => 'Frontend/Backend  Bеб-разработчик.',
    'Jquery, vuejs, Mysql, Yii2, Larave,REST API,  Git' => 'Jquery, vuejs, Mysql, Yii2, Larave,REST API,  Git',
    'O себе' => 'O себе',
    'PhEmailone:' => 'Е-mail: ',
    'SEND' => 'ОТПРАВИТЬ',
    'Website' => 'Website ',
    'Yii2, Laravel' => 'Yii2, Laravel',
    'Английский – A' => 'Английский – A',
    'Блог' => 'Блог',
    'Веб-разработчиком Удаленный' => 'Веб-разработчиком ',
    'Главне' => 'Главная',
    'Доступный' => 'Доступный',
    'Есть  Опыт работы Git' => 'У меня есть опыт работы с Git',
    'Есть  Опыт работы REST API' => 'У меня есть опыт работы с  REST API',
    'Есть Опыт работы  Laravel' => 'Есть  опытом работы от 1 лет.(Laravel framework) ',
    'Есть опытом работы от 1 лет.(yii2 framework)' => 'Есть опытом работы от 1.5 лет.(yii2 framework)',
    'Знание языков' => 'Знание языков',
    'Контактные данные' => 'Контактные данные',
    'Контакть' => 'Контакть',
    'Мои аккаунты в фриланс сайтах: ' => 'Мои аккаунты в фриланс сайтах: ',
    'Мужчина, 22 года, родился 10 июнь 1998' => 'Мужчина, 22 года, родился 10 июнь 1998',
    'Портфолио' => 'Портфолио',
    'себе_uz'=>'Привет всем Краткая информация о себе,
                    Я живу в Ташкенте и Студент 4-курса Ташкентского Университета Информационных Технологий.
                    Я работаю в области веб-программирования
                    В основном я использую',
    'Проектов' => 'Проектов',
    'Реализация' => 'Реализация',
    'Ресуме' => 'Резюме',
    'Русский – разговорный уровень' => 'Русский – разговорный уровень',
    'Счастливые' => 'Счастливые',
    'Узбекский – радной яазик' => 'Узбекский – родная язик',
    'Факты' => 'Факты',
    'Часы поддержки' => 'Часы поддержки',
    'Эльмуродов Жвохир' => 'Эльмуродов Жвохир',
    'Я живу в Ташкенте и Студент 4-курса Ташкентского Университета Информационных Технологий.' => 'Я живу в Ташкенте и Студент 4-курса Ташкентского Университета Информационных Технологий.',
    'Я знаю и использую html, css, bootstrap, javascript,' => 'Я знаю и использую html, css, bootstrap, javascript,',
    'Я работал в Zako МЧЖ в 2018- 2019 году' => 'Я работал в Zako МЧЖ в 2018- 2019 году',
    'Я работаю в OST МЧЖ с 2019 года' => 'Я работаю в  ORIENT SOFTWARE TEAM МЧЖ с 2019 года',
    'для фронтэнда.' => 'для фронтэнда.',
    'клиенты' => 'клиенты',
    'место жительства' => 'место жительства',
    'EMAIL' => 'EMAIL',
    'NAME' => '',
    'Phone' => 'Вызов',
    'message' => 'сообщение',
    'ko\'proq malumot olish uchun rasim ustiga bosing' => 'Нажмите на картинку для получения дополнительной информации',
    'kritlgan vaqti' => 'критическое время',
    'Kurishlar soni' => 'Количество просмотров',
    '' => '@@@@',
    'ru' => '@@russian@@',
    'Телефон' => '@@@@',
];
