<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'O себе' => 'O\'zim haqimda',
    'Блог' => 'Blog',
    'Главне' => 'Asosiy',
    'Портфолио' => 'Portfel',
    'Ресуме' => 'Rezyume',
    'Эльмуродов Жвохир' => 'Elmurodov Javohir',
    ' City : Ташкент' => 'Shahar: Toshkent',
    ' для бэкэнда и' => 'bakend uchun va',
    ' или заказы' => 'yoki buyurtmalar',
    '10 июнь 1998' => '1998 yil 10 iyun',
    'Age' => 'Yoshi',
    'Birthday' => 'Tug\'ilgan kun',
    'Bootstrap, Javascript, Vuejs' => 'Bootstrap, Javascript, Vuejs',
    'Call' => 'Qo\'ng\'iroq',
    'City' => 'Shahar',
    'Degree' => 'Darajasi',
    'EMAIL' => 'EMAIL',
    'Elmurodov_Javohir' => 'Elmurodov_Javohir',
    'Freelance:' => 'Freelance: ',
    'Frontend, Backend разработчик' => 'Frontend, Backend dasturchi',
    'Frontend/Backend  Bеб-разработчик.' => 'Frontend/Backend Veb-dasturchi.',
    'Jquery, vuejs, Mysql, Yii2, Larave,REST API,  Git' => 'Jquery, vuejs, Mysql, Yii2, Larave,REST API,  Git',
    'NAME' => 'NAME',
    'PhEmailone:' => 'Email: ',
    'Phone' => 'Telefon',
    'SEND' => 'JUNATISH',
    'Website' => 'Website',
    'Yii2, Laravel' => 'Yii2, Laravel',
    'message' => 'xabari',
    'Английский – A' => 'Angliyskiy - A',
    'Веб-разработчиком Удаленный' => 'veb-dasturchi',
    'Доступный' => 'Mavjud',
    'Есть  Опыт работы Git' => 'Git dan tajriba bor',
    'Есть  Опыт работы REST API' => 'REST API dan tajriba bor',
    'Есть Опыт работы  Laravel' => 'Laravel  framworkda ishlayman  1 yillik tajribam bor',
    'Есть опытом работы от 1 лет.(yii2 framework)' => 'Yii2 da asosan shu framworkda ishlayman  1.5 yillik tajribam bor',
    'Знание языков' => 'Tillarni bilishi',
    'Контактные данные' => 'MAʼLUMOTLAR',
    'Контакть' => 'Kontakt',
    'Мои аккаунты в фриланс сайтах: ' => 'feerelanser saytlaridagi  accauntlar',
    'Мужчина, 22 года, родился 10 июнь 1998' => 'yoshim 22 da, 1998 yil 10 iyunda tug\'ilganman',
    'себе_uz'=>'Men Toshkentda yashayman va Toshkent Axborot Texnologiyalari Universitetining 4 kurs talabasiman.
                     Men veb-dasturlashda ishlayman
                     Men asosan foydalanaman',
    'Проектов' => 'Loyihalar',
    'Реализация' => 'Amalga oshirilgan',
    'Русский – разговорный уровень' => 'Ruschada - so\'zlasha olaman',
    'Счастливые' => 'Baxtli',
    'Узбекский – радной яазик' => 'Ona tilim O\'zbek tili',
    'Факты' => 'Faktlar',
    'Часы поддержки' => 'Qo\'llab-quvvatlash soatlari',
    'Я живу в Ташкенте и Студент 4-курса Ташкентского Университета Информационных Технологий.' => 'Men Toshkentda yashayman va Toshkent Axborot Texnologiyalari Universitetining 4 kurs talabasiman.',
    'Я знаю и использую html, css, bootstrap, javascript,' => 'Men bilaman va foydalanaman html, css, bootstrap, javascript,',
    'Я работал в Zako МЧЖ в 2018- 2019 году' => 'Men 2018- 2019 yillarda ZAKO MCHJda ishlaganman',
    'Я работаю в OST МЧЖ с 2019 года' => ' ORIENT SOFTWARE TEAM MCHJda 2019 yildan beri ishlayman',
    'для фронтэнда.' => 'frontend uchun',
    'клиенты' => 'mijozlar',
    'место жительства' => 'yashash joyim',
    'ko\'proq malumot olish uchun rasim ustiga bosing' => 'ko\'proq malumot olish uchun rasim ustiga bosing',
    'kritlgan vaqti' => 'kritlgan vaqti',
    'Kurishlar soni' => 'Kurishlar soni',
    '' => '@@@@',
];
