<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'O себе' => 'About',
    'Блог' => 'Blog',
    'Главне' => 'Home',
    'Портфолио' => 'Portfolio',
    'Ресуме' => 'Resume',
    'Эльмуродов Жвохир' => 'Elmurodov Javohir',
    ' City : Ташкент' => 'City: Tashkent',
    ' для бэкэнда и' => 'for the backend and',
    ' или заказы' => 'or orders',
    '10 июнь 1998' => 'June 10, 1998',
    'Age' => 'Age',
    'Birthday' => 'Birthday',
    'Bootstrap, Javascript, Vuejs' => 'Bootstrap, Javascript, Vuejs',
    'Call' => 'Call',
    'City' => 'City',
    'Degree' => 'Degree',
    'EMAIL' => 'EMAIL',
    'Elmurodov_Javohir' => 'Elmurodov_Javohir',
    'Freelance:' => 'Freelance:',
    'Frontend, Backend разработчик' => 'Frontend, Backend Developer',
    'Frontend/Backend  Bеб-разработчик.' => 'Frontend / Backend Web Developer.',
    'Jquery, vuejs, Mysql, Yii2, Larave,REST API,  Git' => 'Jquery, vuejs, Mysql, Yii2, Larave,REST API,  Git',
    'NAME' => 'NAME',
    'PhEmailone:' => 'PhEmailone',
    'Phone' => '',
    'SEND' => 'SEND',
    'Website' => 'Website',
    'Yii2, Laravel' => 'Yii2, Laravel',
    'message' => 'message',
    'Английский – A' => 'English – A',
    'Веб-разработчиком Удаленный' => 'Web Developer',
    'Доступный' => 'Available',
    'Есть  Опыт работы Git' => 'I have experience from Git',
    'Есть  Опыт работы REST API' => 'I have experience from  REST API',
    'Есть Опыт работы  Laravel' => 'There is work experience from 1 year. (Laravel framework)',
    'Есть опытом работы от 1 лет.(yii2 framework)' => 'There is work experience from 1.5 year. (Yii2 framework)',
    'Знание языков' => 'Knowledge of languages',
    'Контактные данные' => 'Contact details',
    'Контакть' => 'Contact',
    'Мои аккаунты в фриланс сайтах: ' => 'My accounts in freelance sites:',
    'Мужчина, 22 года, родился 10 июнь 1998' => 'Man, 22 years old, born June 10, 1998',
    'себе_uz'=>'Hello everyone. Brief information about yourself,
                     I live in Tashkent and am a 4-year student at Tashkent University of Information Technology.
                     I work in web programming
                     I mainly use',
    'Проектов' => 'Projects',
    'Реализация' => 'Implementation',
    'Русский – разговорный уровень' => 'Russian - conversational level',
    'Счастливые' => 'Happy',
    'Узбекский – радной яазик' => 'Uzbek - happy language',
    'Факты' => 'Facts',
    'Часы поддержки' => 'Support Hours',
    'Я живу в Ташкенте и Студент 4-курса Ташкентского Университета Информационных Технологий.' => 'I live in Tashkent and am a 4-year student at Tashkent University of Information Technology.',
    'Я знаю и использую html, css, bootstrap, javascript,' => 'I know and use html, css, bootstrap, javascript,',
    'Я работал в Zako МЧЖ в 2018- 2019 году' => 'I worked at Zako MSF in 2018- 2019',
    'Я работаю в OST МЧЖ с 2019 года' => 'I have been working at  ORIENT SOFTWARE TEAM MFZ since 2019',
    'для фронтэнда.' => 'for the frontend.',
    'клиенты' => 'customers',
    'место жительства' => 'location',
    'ko\'proq malumot olish uchun rasim ustiga bosing' => 'Click on the picture for more information',
    'kritlgan vaqti' => 'critical time',
    'Kurishlar soni' => 'Number of builds',
    '' => '@@@@',
    'en' => '@@engilish@@',
];
